services:
  new-api:
    image: new-api-local:latest
    container_name: new-api-local
    restart: unless-stopped

    ports:
      - "8003:3000"

    command: --log-dir /app/logs

    volumes:
      - /opt/new-api/data:/data
      - /opt/new-api/logs:/app/logs

    environment:
      SQL_DSN: "root:xxxxx@tcp(mysql8.2:3306)/new-api?charset=utf8mb4&parseTime=True&loc=Local"
      REDIS_CONN_STRING: "redis://redis:6379"
      TZ: Asia/Shanghai
    networks:
      - my_network

networks:
  my_network:
    external: true
