services:
  new-api:
    image: new-api-local:latest
    container_name: new-api-local
    restart: unless-stopped

    ports:
      - "8003:3000"

    command: --log-dir /app/logs

    volumes:
      - /opt/new-api/data:/data
      - /opt/new-api/logs:/app/logs

    environment:
      SQL_DSN: "root:xxxxx@tcp(mysql8.2:3306)/new-api?charset=utf8mb4&parseTime=True&loc=Local"
      REDIS_CONN_STRING: "redis://redis:6379"
      TZ: Asia/Shanghai
      ERROR_LOG_ENABLED: "true"
      BATCH_UPDATE_ENABLED: "true"
      NODE_NAME: "new-api-node-1"
#      LOG_SQL_DSN: "postgresql://root:123456@postgres:5432/new-api-log"
#      LOG_SQL_DSN: "clickhouse://default:123456@clickhouse:9000/new_api_logs"
#      LOG_SQL_CLICKHOUSE_TTL_DAYS: "0"
#      STREAMING_TIMEOUT: "300"
#      RELAY_IDLE_CONN_TIMEOUT: "90"
#      SESSION_SECRET: "random_string"
#      SESSION_COOKIE_SECURE: "true"
#      SESSION_COOKIE_TRUSTED_URL: "https://example.com,https://admin.example.com"
#      TRUSTED_PROXIES: "172.20.0.0/16"
#      USER_SESSION_ACTIVE_LIMIT: "50"
#      USER_SESSION_ISSUANCE_LIMIT: "100"
#      USER_SESSION_ISSUANCE_WINDOW_SECONDS: "86400"
#      USER_SESSION_REVOKED_RETENTION_DAYS: "7"
#      USER_SESSION_HOURLY_ALERT_THRESHOLD: "5000"
#      SYNC_FREQUENCY: "60"
#      GOOGLE_ANALYTICS_ID: "G-XXXXXXXXXX"
#      UMAMI_WEBSITE_ID: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
#      UMAMI_SCRIPT_URL: "https://analytics.umami.is/script.js"

    networks:
      - my_network

networks:
  my_network:
    external: true
